services:
  database:
    container_name: database
    image: mariadb:10.6-focal
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./database_datas:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
  database_test:
    container_name: database_test
    image: mariadb:10.6-focal
    ports:
      - 3307:3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_DATABASE=test